local function desc(description)
  return { noremap = true, silent = true, desc = description }
end
vim.keymap.set('n', '<space>ss', function()
  vim.cmd.ISwap()
end, desc('[iswap] swap parameters'))
vim.keymap.set('n', '<space>sw', function()
  vim.cmd.ISwapWith()
end, desc('[iswap] swap parameter with'))
vim.keymap.set('n', '<space>snn', function()
  vim.cmd.ISwapNode()
end, desc('[iswap] swap nodes'))
vim.keymap.set('n', '<space>snw', function()
  vim.cmd.ISwapNodeWith()
end, desc('[iswap] swap node with'))
vim.keymap.set('n', '<space>smm', function()
  vim.cmd.IMove()
end, desc('[iswap] move'))
vim.keymap.set('n', '<space>smw', function()
  vim.cmd.IMoveWith()
end, desc('[iswap] move with'))
