local keymap_opts = { noremap = true, silent = true }
vim.keymap.set('n', '<space>ss', function()
  vim.cmd.ISwap()
end, keymap_opts)
vim.keymap.set('n', '<space>sw', function()
  vim.cmd.ISwapWith()
end, keymap_opts)
vim.keymap.set('n', '<space>snn', function()
  vim.cmd.ISwapNode()
end, keymap_opts)
vim.keymap.set('n', '<space>snw', function()
  vim.cmd.ISwapNodeWith()
end, keymap_opts)
vim.keymap.set('n', '<space>smm', function()
  vim.cmd.IMove()
end, keymap_opts)
vim.keymap.set('n', '<space>smw', function()
  vim.cmd.IMoveWith()
end, keymap_opts)
