require('hardtime').setup {
  max_time = 1000,
  max_count = 3,
  disable_mouse = true,
  hint = true,
  notification = true,
  allow_different_key = false,
  restricted_keys = {
    ['h'] = { 'n', 'x' },
    ['j'] = { 'n', 'x' },
    ['k'] = { 'n', 'x' },
    ['l'] = { 'n', 'x' },
    ['gj'] = { 'n', 'x' },
    ['gk'] = { 'n', 'x' },
    ['<CR>'] = { 'n', 'x' },
    ['<C-M>'] = { 'n', 'x' },
    ['<C-N>'] = { 'n', 'x' },
  },
  disabled_filetypes = {
    'qf',
    'netrw',
    'NeogitStatus',
    'DiffviewFilePanel',
    'tsplayground',
  },
}
