require('mrcjk.deprication-warnings')
require('mrcjk.native-plugins')
require('mrcjk.settings')
require('mrcjk.autocommands')
require('mrcjk.keymaps')
require('mrcjk.commands')
require('mrcjk.ftdetect')
require('mrcjk.neovide')
