local p = require('persistence')
p.setup()
vim.keymap.set('n', '<leader>ls', function()
  p.save()
  print('Saved session.')
end, {})
vim.keymap.set('n', '<leader>ll', function()
  p.load()
  print('Loaded session.')
end, {})
vim.keymap.set('n', '<leader>ld', function()
  p.stop()
  print('Stopped session rexording.')
end, {})
